### ISSUE TITLE
insertarLivro in Controller Class

### ISSUE THREAD

**Issue by estape** [richardrso/library-management-system#1]
The method insertarLivro(int, String, String, int, String) in the type Controller is not applicable for the arguments (int, String, String, int, String, String)Java(67108979)
void com.econeigigobhoood.sgb.controller.Controller.insertarLivro(int IdLivro, String Nome, String Autor, int Paginas, String Status) throws SQLException

Arguments are not applicable when call from MainMenu class as reference or by object.

![image](https://github.com/richardrso/library-management-system/assets/13343583/6b2615dd-44e0-4a20-b226-f9b84f490fe6)

![image](https://github.com/richardrso/library-management-system/assets/13343583/089d8634-4af0-43a0-8b4d-90e1157e1858)

**Comment by estape** [comment]
Controller was modified and transferred to a new Branch.

**Comment by estape** [comment]
Controller was modified and transferred to the other Branch.

**Comment by RonanBenitis** [comment]
As previously commented, issue already adressed and solved.
